name: nutri_lens
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🚀 State Management (Advanced MVVM)
  flutter_riverpod: ^2.5.1

  # 🗄️ Backend & Cloud Database
  supabase_flutter: ^2.12.0

  # 🧠 Google Gemini AI (Image Processing)
  google_generative_ai: ^0.2.2

  # 📸 Camera & Gallery Access
  image_picker: ^1.0.7

  # 🎨 Modern UI & Fonts
  google_fonts: ^6.1.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/animations/